name: chating
description: "A Flutter video calling app with ZegoCloud and Firebase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_database: ^11.0.2
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.2.3

  # Google Sign In
  google_sign_in: ^6.2.1

  # ZegoCloud
  zego_uikit_prebuilt_call: ^4.23.1
  zego_uikit_signaling_plugin: ^2.8.21
  zego_zpns: ^2.6.0
  zego_zim: ^2.29.0
  zego_uikit: any

  # Native Calling UI
  flutter_callkit_incoming: ^2.0.3

  # UI
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.4.10
  image_picker: ^1.2.1
  cloudinary_public: any
  google_mlkit_face_detection: ^0.11.0
  http: ^1.1.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.3
  device_info_plus: ^11.5.0
  uuid: ^4.3.3
  audioplayers: ^6.0.0
  flutter_foreground_task: ^8.17.0
  vibration: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ringtone/incoming.mp3
